INSERT INTO api_product (id, name, description, barcode, brand, material, care_instructions, price, sale_price, start_sale_date, end_sale_date, stock, weight, dimensions, sizes, colors, status, is_featured, is_new_arrival, is_on_sale, rating, num_reviews, quantity_sold, main_image, video_url, meta_title, meta_description, created_at, updated_at, slug, category_id, user_id, sku) VALUES (4, 'Classic Pullover Hoodie', null, null, '', '', '', 75, null, null, null, 182, null, '', 'S,M,L', 'BLACK,WHITE,GREY,RED', 'ACTIVE', 0, 0, 0, 0, 0, 0, '', null, '', '', '2024-12-17 04:17:05.156085', '2024-12-17 13:33:47.151185', 'classic-pullover-hoodie', 10, 3, null);
INSERT INTO api_product (id, name, description, barcode, brand, material, care_instructions, price, sale_price, start_sale_date, end_sale_date, stock, weight, dimensions, sizes, colors, status, is_featured, is_new_arrival, is_on_sale, rating, num_reviews, quantity_sold, main_image, video_url, meta_title, meta_description, created_at, updated_at, slug, category_id, user_id, sku) VALUES (5, 'Elegant Metal Timepiece', null, null, 'ChronoCraft', '', '', 125, null, null, null, 20, 150, '22cm x 4cm x 1cm', 'MINI,MIDSIZE', 'SILVER', 'ACTIVE', 0, 0, 0, 0, 0, 0, '', null, '', '', '2024-12-17 12:28:20.351735', '2024-12-17 13:42:56.205568', 'elegant-metal-timepiece', 6, 3, null);
INSERT INTO api_product (id, name, description, barcode, brand, material, care_instructions, price, sale_price, start_sale_date, end_sale_date, stock, weight, dimensions, sizes, colors, status, is_featured, is_new_arrival, is_on_sale, rating, num_reviews, quantity_sold, main_image, video_url, meta_title, meta_description, created_at, updated_at, slug, category_id, user_id, sku) VALUES (6, 'Classic Leather Handbag', null, null, 'LuxeCraft', 'Leather', '', 120, null, null, null, 40, 525, '30cm x 25cm x 15cm', 'STANDARD', 'BROWN', 'ACTIVE', 0, 0, 0, 0, 0, 0, '', null, '', '', '2024-12-17 13:38:04.514616', '2024-12-17 13:43:06.651482', 'classic-leather-handbag', 6, 3, null);
INSERT INTO api_product (id, name, description, barcode, brand, material, care_instructions, price, sale_price, start_sale_date, end_sale_date, stock, weight, dimensions, sizes, colors, status, is_featured, is_new_arrival, is_on_sale, rating, num_reviews, quantity_sold, main_image, video_url, meta_title, meta_description, created_at, updated_at, slug, category_id, user_id, sku) VALUES (7, 'Classic Leather Tote Bag', null, null, 'LuxeCraft', 'Leather', '', 150, null, null, null, 12, 700, '40cm x 30cm x 15cm', 'STANDARD', 'BEIGE', 'INACTIVE', 0, 0, 0, 0, 0, 0, '', null, '', '', '2024-12-17 13:40:29.936268', '2024-12-17 13:51:42.170328', 'classic-leather-tote-bag', 9, 3, null);
INSERT INTO api_product (id, name, description, barcode, brand, material, care_instructions, price, sale_price, start_sale_date, end_sale_date, stock, weight, dimensions, sizes, colors, status, is_featured, is_new_arrival, is_on_sale, rating, num_reviews, quantity_sold, main_image, video_url, meta_title, meta_description, created_at, updated_at, slug, category_id, user_id, sku) VALUES (10, 'Urban Elegance', null, null, '', '', '', 96, null, null, null, 44, 340, '25cm x 18cm x 8cm', 'STANDARD,MIDSIZE', 'BEIGE', 'ACTIVE', 0, 0, 0, 0, 0, 0, '', null, '', '', '2024-12-17 13:45:14.197615', '2024-12-17 13:53:09.433571', 'urban-elegance', 9, 3, null);
INSERT INTO api_product (id, name, description, barcode, brand, material, care_instructions, price, sale_price, start_sale_date, end_sale_date, stock, weight, dimensions, sizes, colors, status, is_featured, is_new_arrival, is_on_sale, rating, num_reviews, quantity_sold, main_image, video_url, meta_title, meta_description, created_at, updated_at, slug, category_id, user_id, sku) VALUES (11, 'Luxury Leather Backpack', null, null, 'TravelLux', 'Leather', '', 180, null, null, null, 30, 900, '45cm x 35cm x 15cm', 'BIGSIZE', 'GREY', 'ACTIVE', 0, 0, 0, 0, 0, 0, '', null, '', '', '2024-12-17 13:49:17.008826', '2024-12-17 13:52:58.877520', 'luxury-leather-backpack', 9, 3, null);
INSERT INTO api_product (id, name, description, barcode, brand, material, care_instructions, price, sale_price, start_sale_date, end_sale_date, stock, weight, dimensions, sizes, colors, status, is_featured, is_new_arrival, is_on_sale, rating, num_reviews, quantity_sold, main_image, video_url, meta_title, meta_description, created_at, updated_at, slug, category_id, user_id, sku) VALUES (12, 'Compact Leather Sling Bag', null, null, 'UrbanEase', '', '', 99, null, null, null, 4, 340, '25cm x 18cm x 8cm', 'SMALL', 'GREY', 'ACTIVE', 0, 0, 0, 0, 0, 0, '', null, '', '', '2024-12-17 13:52:46.184363', '2024-12-17 13:53:22.139681', 'compact-leather-sling-bag', 9, 3, null);
INSERT INTO api_product (id, name, description, barcode, brand, material, care_instructions, price, sale_price, start_sale_date, end_sale_date, stock, weight, dimensions, sizes, colors, status, is_featured, is_new_arrival, is_on_sale, rating, num_reviews, quantity_sold, main_image, video_url, meta_title, meta_description, created_at, updated_at, slug, category_id, user_id, sku) VALUES (13, 'Modern Slim-Fit Men''s Blazer', 'Single-breasted, notched lapel, two buttons', null, 'Slim-Fit', 'Breathable Fabric', '', 225, null, null, null, 9, 200, '', 'XL,L', 'DARK GREY', 'ACTIVE', 0, 0, 0, 0, 0, 0, '', null, '', '', '2024-12-17 13:57:25.212665', '2024-12-17 13:57:40.522156', 'modern-slim-fit-mens-blazer', 5, 3, null);
INSERT INTO api_product (id, name, description, barcode, brand, material, care_instructions, price, sale_price, start_sale_date, end_sale_date, stock, weight, dimensions, sizes, colors, status, is_featured, is_new_arrival, is_on_sale, rating, num_reviews, quantity_sold, main_image, video_url, meta_title, meta_description, created_at, updated_at, slug, category_id, user_id, sku) VALUES (14, 'Stylish Unisex Oversized T-Shirt', 'Relaxed fit, round neckline, short sleeves', null, 'RD', 'Soft Cotton', '', 30, null, null, null, 0, 100, '', 'XL,XXL,L,S,M', 'CREAM', 'INACTIVE', 0, 0, 0, 0, 0, 0, '', null, '', '', '2024-12-17 13:58:49.829543', '2024-12-17 14:07:56.460011', 'stylish-unisex-oversized-t-shirt', 5, 3, null);
INSERT INTO api_product (id, name, description, barcode, brand, material, care_instructions, price, sale_price, start_sale_date, end_sale_date, stock, weight, dimensions, sizes, colors, status, is_featured, is_new_arrival, is_on_sale, rating, num_reviews, quantity_sold, main_image, video_url, meta_title, meta_description, created_at, updated_at, slug, category_id, user_id, sku) VALUES (15, 'Premium Minimalist Men''s Hoodie', 'Kangaroo pocket, ribbed cuffs, adjustable hood', null, 'BetaM', 'High-quality Cotton', '', 88, null, null, null, 90, 420, '', 'M,XL,XXL', 'CHARCOAL GREY,NAVY BLUE', 'ACTIVE', 0, 0, 0, 0, 0, 0, '', null, '', '', '2024-12-17 14:04:47.964219', '2024-12-17 14:34:56.483217', 'premium-minimalist-mens-hoodie', 10, 3, null);
INSERT INTO api_product (id, name, description, barcode, brand, material, care_instructions, price, sale_price, start_sale_date, end_sale_date, stock, weight, dimensions, sizes, colors, status, is_featured, is_new_arrival, is_on_sale, rating, num_reviews, quantity_sold, main_image, video_url, meta_title, meta_description, created_at, updated_at, slug, category_id, user_id, sku) VALUES (16, 'UrbanEase Oversized T-Shirt', 'Ultra-soft, breathable cotton fabric for comfort.
Classic crew neck with iridescent collar trim for a modern, stylish twist.
Wide, drop-shoulder sleeves and loose fit for a relaxed urban aesthetic.
Lightweight design, perfect for daily wear or layering.', null, 'UrbanEase', 'Premium Cotton Blend', 'Machine wash cold, gentle cycle.
Do not iron over iridescent details.', 50, null, null, null, 63, 220, '', 'OVERSIZED,FIXED', 'SAND BEIGE', 'ACTIVE', 0, 0, 0, 0, 0, 0, '', null, '', '', '2024-12-17 14:09:24.860203', '2024-12-17 14:16:41.283731', 'urbanease-oversized-t-shirt', 5, 3, null);
INSERT INTO api_product (id, name, description, barcode, brand, material, care_instructions, price, sale_price, start_sale_date, end_sale_date, stock, weight, dimensions, sizes, colors, status, is_featured, is_new_arrival, is_on_sale, rating, num_reviews, quantity_sold, main_image, video_url, meta_title, meta_description, created_at, updated_at, slug, category_id, user_id, sku) VALUES (17, 'Minimalist Leather Sneakers', 'Streamlined silhouette
Durable, textured sole
Matching white laces for a clean minimalist look
Perfect for casual wear and versatile styling', null, 'LinemO', 'Premium White Leathe', '', 80, null, null, null, 6, 665, '', 'L', 'WHITE WITH SUBTLE STITCHING', 'ACTIVE', 0, 0, 0, 0, 0, 0, '', null, '', '', '2024-12-17 14:15:10.601763', '2024-12-17 14:17:18.456227', 'minimalist-leather-sneakers', 8, 3, null);
INSERT INTO api_product (id, name, description, barcode, brand, material, care_instructions, price, sale_price, start_sale_date, end_sale_date, stock, weight, dimensions, sizes, colors, status, is_featured, is_new_arrival, is_on_sale, rating, num_reviews, quantity_sold, main_image, video_url, meta_title, meta_description, created_at, updated_at, slug, category_id, user_id, sku) VALUES (18, 'Urban High-Top Sneakers', 'Chunky, textured sole for streetwear style
Subtle embossed detail around the ankle
Padded design for comfort
Ideal for streetwear or casual urban fashion', null, 'Ur', 'Premium Black Matte Leather', '', 110, null, null, null, 12, 670, '', 'XL', 'MATTE BLACK', 'ACTIVE', 0, 0, 0, 0, 0, 0, '', null, '', '', '2024-12-17 14:16:21.961728', '2024-12-17 14:17:29.839926', 'urban-high-top-sneakers', 8, 3, null);
INSERT INTO api_product (id, name, description, barcode, brand, material, care_instructions, price, sale_price, start_sale_date, end_sale_date, stock, weight, dimensions, sizes, colors, status, is_featured, is_new_arrival, is_on_sale, rating, num_reviews, quantity_sold, main_image, video_url, meta_title, meta_description, created_at, updated_at, slug, category_id, user_id, sku) VALUES (19, 'Low-Top Suede Sneakers', 'Sleek silhouette with beige laces
Subtle stitching details for elegance
Durable, cushioned sole for everyday use
Occasion: Stylish and casual for everyday wear', null, 'SuedeX', 'Soft Suede', '', 90, null, null, null, 23, 670, '', 'XL', 'EARTHY BROWN WITH WHITE RUBBER SOLE', 'ACTIVE', 0, 0, 0, 0, 0, 0, '', null, '', '', '2024-12-17 14:18:34.905608', '2024-12-17 14:18:46.327218', 'low-top-suede-sneakers', 8, 3, null);
INSERT INTO api_product (id, name, description, barcode, brand, material, care_instructions, price, sale_price, start_sale_date, end_sale_date, stock, weight, dimensions, sizes, colors, status, is_featured, is_new_arrival, is_on_sale, rating, num_reviews, quantity_sold, main_image, video_url, meta_title, meta_description, created_at, updated_at, slug, category_id, user_id, sku) VALUES (20, 'Urban Khaki Chinos', 'Fit: Slim-Fit, Modern
Hidden zipper fly and clean waistband
Side pockets for utility
Versatile styling for smart-casual wear
Occasion: Suitable for casual office wear or weekend outings', null, 'ChinoisTown', 'Earthy Khaki', '', 72, null, null, null, 23, 336, '', '36', 'BEIGE', 'ACTIVE', 0, 0, 0, 0, 0, 0, '', null, '', '', '2024-12-17 14:26:42.785857', '2024-12-17 14:40:56.734735', 'urban-khaki-chinos', 11, 3, null);
INSERT INTO api_product (id, name, description, barcode, brand, material, care_instructions, price, sale_price, start_sale_date, end_sale_date, stock, weight, dimensions, sizes, colors, status, is_featured, is_new_arrival, is_on_sale, rating, num_reviews, quantity_sold, main_image, video_url, meta_title, meta_description, created_at, updated_at, slug, category_id, user_id, sku) VALUES (22, 'Men''s Slim-Fit Jogger Trousers', 'Tapered, Slim-Fit
Elastic cuffs and adjustable drawstring waistband
Casual silhouette with modern details
Perfect balance of comfort and style
Occasion: Ideal for lounging, light sportswear, or casual wear', null, 'EXSport', 'Premium Cotton Fabric', '', 65, null, null, null, 69, 400, '', '30,31,32', 'CHARCOAL GREY,WHITE', 'ACTIVE', 0, 0, 0, 0, 0, 0, '', null, '', '', '2024-12-17 14:29:35.017032', '2024-12-17 14:41:29.412040', 'mens-slim-fit-jogger-trousers', 11, 3, null);
INSERT INTO api_product (id, name, description, barcode, brand, material, care_instructions, price, sale_price, start_sale_date, end_sale_date, stock, weight, dimensions, sizes, colors, status, is_featured, is_new_arrival, is_on_sale, rating, num_reviews, quantity_sold, main_image, video_url, meta_title, meta_description, created_at, updated_at, slug, category_id, user_id, sku) VALUES (23, 'Women''s Tailored Ankle Trousers', 'Fit: Slim-Fit, Cropped Length
Minimalist waistband and side pockets
Tailored for a clean, modern silhouette
Chic and versatile for professional or semi-formal occasions
Occasion: Great for business casual or evening wear', null, 'TailorSeries', 'Stretch Cotton Blend', '', 74, null, null, null, 26, 500, '', '30,32,34', 'SOFT PASTEL PINK', 'ACTIVE', 0, 0, 0, 0, 0, 0, '', null, '', '', '2024-12-17 14:30:52.671502', '2024-12-17 14:40:29.832003', 'womens-tailored-ankle-trousers', 11, 3, null);
INSERT INTO api_product (id, name, description, barcode, brand, material, care_instructions, price, sale_price, start_sale_date, end_sale_date, stock, weight, dimensions, sizes, colors, status, is_featured, is_new_arrival, is_on_sale, rating, num_reviews, quantity_sold, main_image, video_url, meta_title, meta_description, created_at, updated_at, slug, category_id, user_id, sku) VALUES (24, 'Men''s Cargo Trousers', 'Fit: Relaxed, Straight-Leg
Multiple utility pockets for functionality
Reinforced stitching for a rugged look
Practical and stylish design
Occasion: Perfect for outdoor activities or casual daily wear', null, 'CargoMen', 'Stretch Cotton Blend', '', 65, null, null, null, 40, 340, '', '33,34,35', 'MUTED OLIVE GREEN', 'ACTIVE', 0, 0, 0, 0, 0, 0, '', null, '', '', '2024-12-17 14:33:16.644768', '2024-12-17 14:39:47.902601', 'mens-cargo-trousers', 11, 3, null);
INSERT INTO api_product (id, name, description, barcode, brand, material, care_instructions, price, sale_price, start_sale_date, end_sale_date, stock, weight, dimensions, sizes, colors, status, is_featured, is_new_arrival, is_on_sale, rating, num_reviews, quantity_sold, main_image, video_url, meta_title, meta_description, created_at, updated_at, slug, category_id, user_id, sku) VALUES (25, 'Timeless Minimalist Wristwatch', 'Slim, sleek design for a modern look
Clean white watch face without numbers
Subtle hour and minute hands for a minimalist aesthetic
Stainless steel case for durability and elegance
Occasion:

Perfect for formal events, professional settings, or everyday wear', null, 'Timeless', 'Case: Stainless Steel; Strap: High-Quality Black Leather', 'Avoid water exposure to leather
Clean with a soft, dry cloth', 150, null, null, null, 5, 668, '', 'FITS', 'SILVER', 'ACTIVE', 0, 0, 0, 0, 0, 0, '', null, '', '', '2024-12-17 14:39:08.839165', '2024-12-17 14:40:03.558518', 'timeless-minimalist-wristwatch', 6, 3, null);
