# Generated by Django 5.1.1 on 2024-12-25 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModulePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=255)),
                ('lib', models.CharField(max_length=255)),
                ('logo_url', models.URLField()),
                ('test_mode', models.CharField(choices=[('on', 'On'), ('off', 'Off')], default='on', max_length=10)),
                ('id_tpv', models.CharField(max_length=10)),
                ('client_id_test', models.CharField(blank=True, max_length=255, null=True)),
                ('client_secret_test', models.CharField(blank=True, max_length=255, null=True)),
                ('merchant_id_test', models.CharField(blank=True, max_length=255, null=True)),
                ('cle_api_test', models.CharField(blank=True, max_length=255, null=True)),
                ('client_id_prod', models.CharField(blank=True, max_length=255, null=True)),
                ('client_secret_prod', models.CharField(blank=True, max_length=255, null=True)),
                ('merchant_id_prod', models.CharField(blank=True, max_length=255, null=True)),
                ('cle_api_prod', models.CharField(blank=True, max_length=255, null=True)),
                ('site_code_viva', models.CharField(blank=True, max_length=10, null=True)),
                ('payment_form_color', models.CharField(max_length=7)),
                ('platform_url', models.URLField(blank=True, null=True)),
                ('connect_token_url_test', models.URLField(blank=True, null=True)),
                ('connect_token_url_prod', models.URLField(blank=True, null=True)),
                ('base_url_test', models.URLField(blank=True, null=True)),
                ('base_url_prod', models.URLField(blank=True, null=True)),
                ('base_url_test2', models.URLField(blank=True, null=True)),
                ('base_url_prod2', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='is_default',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='user',
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='method_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='method_type',
            field=models.CharField(choices=[('CASH', 'Cash'), ('CREDIT_CARD', 'Credit Card'), ('BANK_TRANSFER', 'Bank Transfer')], max_length=50),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='module_payment',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='api.modulepayment'),
            preserve_default=False,
        ),
    ]
