# Generated by Django 5.1.1 on 2024-12-17 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='order',
        ),
    ]
