# Generated by Django 5.1.1 on 2024-10-12 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='seller',
        ),
        migrations.AddField(
            model_name='product',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(choices=[('User', 'User'), ('Address', 'Address'), ('Category', 'Category'), ('Tag', 'Tag'), ('Product', 'Product'), ('ProductImage', 'ProductImage'), ('Cart', 'Cart'), ('CartItem', 'CartItem'), ('Wishlist', 'Wishlist'), ('WishlistItem', 'WishlistItem'), ('Order', 'Order'), ('OrderItem', 'OrderItem'), ('Review', 'Review'), ('ReviewImage', 'ReviewImage'), ('Coupon', 'Coupon'), ('LoyaltyPoint', 'LoyaltyPoint'), ('Transaction', 'Transaction'), ('MessageThread', 'MessageThread'), ('Message', 'Message'), ('Promotion', 'Promotion'), ('Notification', 'Notification'), ('ReturnRequest', 'ReturnRequest'), ('ShippingMethod', 'ShippingMethod'), ('PaymentMethod', 'PaymentMethod'), ('SellerProfile', 'SellerProfile'), ('ActivityLog', 'ActivityLog')], max_length=50)),
                ('action', models.CharField(choices=[('view', 'View'), ('add', 'Add'), ('change', 'Change'), ('delete', 'Delete')], max_length=10)),
                ('allowed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
                'unique_together': {('user', 'model_name', 'action')},
            },
        ),
    ]
