# Generated by Django 5.1.1 on 2024-10-16 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_role'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Permission',
            new_name='UserPermission',
        ),
    ]
