# Generated by Django 5.1.1 on 2024-12-17 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_stockvariant_image_productimage_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='color',
        ),
    ]
