# Generated by Django 5.1.1 on 2024-12-17 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_productimage_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockvariant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='variant_images/'),
        ),
    ]
