# Generated by Django 5.1.1 on 2024-12-17 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_stockvariant_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockvariant',
            name='image',
        ),
        migrations.CreateModel(
            name='ColorImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='color_images/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_images', to='api.product')),
            ],
            options={
                'verbose_name': 'Color Image',
                'verbose_name_plural': 'Color Images',
                'unique_together': {('product', 'color')},
            },
        ),
    ]
