# Generated by Django 5.1.1 on 2024-11-18 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
