# Generated by Django 5.1.1 on 2024-11-27 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_address_user_customer_address_customer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['id']},
        ),
    ]
