# Generated by Django 5.1.1 on 2024-12-08 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_product_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activitylog',
            old_name='description',
            new_name='context',
        ),
        migrations.AddField(
            model_name='activitylog',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='model',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
