# Generated by Django 5.1.1 on 2024-12-08 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_activitylog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, unpack_ipv4=True),
        ),
    ]
