# Generated by Django 5.1.1 on 2024-12-08 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_productimage_product'),
        ('api', '0018_alter_activitylog_ip_address'),
    ]

    operations = [
    ]
