# Generated by Django 5.1.1 on 2024-12-09 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_merge_20241208_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='district',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.RenameField(
            model_name='address',
            old_name='city',
            new_name='ward',
        )
    ]
