# Generated by Django 5.1.1 on 2024-12-12 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_orderitem_seller_alter_sellerprofile_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockvariant',
            options={},
        ),
    ]
