# Generated by Django 5.1.1 on 2024-12-12 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_stockvariant_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockvariant',
            options={'ordering': ['-created_at'], 'verbose_name': 'Stock Variant', 'verbose_name_plural': 'Stock Variants'},
        ),
        migrations.AlterUniqueTogether(
            name='stockvariant',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='stockvariant',
            constraint=models.UniqueConstraint(fields=('product', 'stock', 'variant_name'), name='unique_stock_variant'),
        ),
    ]
