# Generated by Django 5.1.1 on 2024-12-13 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_stockvariant_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockvariant',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='stockvariant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='variant_images/'),
        ),
    ]
