# Generated by Django 5.1.1 on 2024-12-09 13:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_product_description_alter_product_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='api.order'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='api.customer'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='StockVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_name', models.CharField(help_text='Example: S - Red', max_length=255, verbose_name='Variant Name')),
                ('quantity', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantity in Stock')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_variants', to='api.product', verbose_name='Product')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_variants', to='api.stock', verbose_name='Stock Location')),
            ],
            options={
                'verbose_name': 'Stock Variant',
                'verbose_name_plural': 'Stock Variants',
                'ordering': ['-created_at'],
                'unique_together': {('product', 'stock', 'variant_name')},
            },
        ),
    ]
